### ISSUE TITLE
Occasional NullPointerException

### ISSUE THREAD

**Issue by madflow** [madflow/flow-netbeans-markdown#58]
I haven't found a way to reproduce this yet. Maybe this is just on a linux machine..

The NPE occurs when previewing a .md file.

Tested with this commit:

https://github.com/madflow/flow-netbeans-markdown/commit/88aaafc656f6c3fc5919914f5e3fbc98d7319b64

```
java.lang.NullPointerException
    at javafx.scene.Scene$ScenePulseListener.synchronizeSceneProperties(Scene.java:2323)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2417)
    at com.sun.javafx.tk.Toolkit$3.run(Toolkit.java:321)
    at com.sun.javafx.tk.Toolkit$3.run(Toolkit.java:319)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:319)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:348)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:479)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:460)
    at com.sun.javafx.tk.quantum.QuantumToolkit$13.run(QuantumToolkit.java:327)
[catch] at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.access$200(GtkApplication.java:48)
    at com.sun.glass.ui.gtk.GtkApplication$6$1.run(GtkApplication.java:149)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Ditso6** [comment]
Did you find a work around?

**Comment by madflow** [comment]
I have not - I could not reproduce it. To me it seemed like a random error, which could be caused by a timeout when rendering a document. Pretty vague.

Can you reproduce this every time you try to render a certain document?

**Comment by Ditso6** [comment]
Seems to be a javafx upstream bug https://javafx-jira.kenai.com/browse/RT-37862
